#!/usr/bin/env python3
import json
from pathlib import Path

root = Path("/workspace/src/lib/story.json")
story = json.loads(root.read_text())

def page(id, image, file, title, texts):
    return {"id": id, "image": image, "file": file, "title": title, "text": texts}


def t(pre_vi, pre_en, pri_vi, pri_en, int_vi, int_en, sen_vi, sen_en):
    return {
        "preschool": {"vi": pre_vi, "en": pre_en},
        "primary": {"vi": pri_vi, "en": pri_en},
        "intermediate": {"vi": int_vi, "en": int_en},
        "senior": {"vi": sen_vi, "en": sen_en},
    }


s2_pages = [
    page(
        "s2-cover",
        "/illustrations/s2-00.jpg",
        "s2-page-00",
        {"vi": "Mùa đất", "en": "Earth Season"},
        t(
            "Đây là chuyện Aang. Mùa hai. Aang tìm thầy đất.",
            "This is Aang. Season two. Aang looks for an earth teacher.",
            "Đây là mùa hai của Aang. Aang cần một người dạy điều khiển đất.",
            "This is Aang's second season. Aang needs someone to teach him to move the earth.",
            "Mùa đất bắt đầu. Aang, Katara và Sokka bay qua Thổ quốc để tìm một thổ nhân dạy thổ thuật.",
            "The Earth season begins. Aang, Katara, and Sokka fly through the Earth Kingdom to find an earthbender who can teach him.",
            "Mùa đất mở ra trên những triền núi xanh. Aang phải tìm một thổ nhân — người sẽ dạy cậu đứng vững trên mặt đất, như gió đã dạy cậu bay.",
            "The Earth season opens over green mountains. Aang must find an earthbender — someone who will teach him to stand as firmly as the wind once taught him to fly.",
        ),
    ),
    page(
        "s2-travel",
        "/illustrations/s2-01.jpg",
        "s2-page-01",
        {"vi": "Bay đất", "en": "Over Earth"},
        t(
            "Các bạn bay với Appa. Chỗ đất rộng lắm. Tìm thầy nha.",
            "The friends fly with Appa. The earth place is so big. They look for a teacher.",
            "Các bạn bay trên Appa qua đồi xanh. Họ hỏi mọi người: ai dạy được đất?",
            "The friends fly on Appa over green hills. They ask people: who can teach earth?",
            "Đội Avatar đi xuyên Thổ quốc. Đường dài, núi cao, và Aang vẫn chưa gặp thầy thổ thuật của mình.",
            "Team Avatar crosses the Earth Kingdom. The road is long, the mountains high, and Aang still has not met his earthbending teacher.",
            "Họ lướt trên lưng Appa, cắt những dải đất rộng. Mỗi ngôi làng là một câu hỏi. Thầy ở đâu, khi cả một quốc gia đang run dưới gót Hỏa quốc?",
            "They glide on Appa's back across wide lands. Every village is a question. Where is the teacher, when a whole nation trembles under the Fire Nation's step?",
        ),
    ),
    page(
        "s2-toph",
        "/illustrations/s2-02.jpg",
        "s2-page-02",
        {"vi": "Toph", "en": "Toph"},
        t(
            "Có bé Toph. Toph nhỏ xíu. Toph hông thấy. Toph đá khỏe lắm.",
            "This is Toph. Toph is little. Toph cannot see. Toph is so strong with rocks.",
            "Họ gặp Toph. Toph nhỏ và không nhìn thấy. Nhưng Toph đá bể đá to.",
            "They met Toph. Toph is small and cannot see. But Toph can break big rocks.",
            "Toph Bé bước ra từ đấu trường. Cô mù, nhưng cô đọc đất như chữ. Không ai mạnh bằng cô.",
            "Little Toph stepped out of the arena. She is blind, but she reads the ground like a page. No one is stronger than she is.",
            "Toph Bé — thổ nhân mù, chân trần trên đá — làm cả đấu trường im. Cô không cần mắt. Trái đất nói với cô trước.",
            "Little Toph — a blind earthbender, barefoot on stone — silenced the arena. She did not need eyes. The earth spoke to her first.",
        ),
    ),
    page(
        "s2-teach",
        "/illustrations/s2-03.jpg",
        "s2-page-03",
        {"vi": "Học đá", "en": "Learn Earth"},
        t(
            "Toph dạy Aang. Aang giậm chân. Đá nhảy lên. Aang vui lắm.",
            "Toph taught Aang. Aang stamped his foot. The rocks jumped. Aang was so happy.",
            "Toph dạy Aang đứng vững và đẩy đá. Aang học chậm, rồi đá nghe lời.",
            "Toph taught Aang to stand firm and push the rocks. Aang learned slowly, then the rocks listened.",
            "Trong hẻm núi, Toph dạy Aang thổ thuật: chân bám đất, ý chí đẩy núi. Lần đầu cậu cảm thấy mặt đất trả lời.",
            "In a canyon, Toph taught Aang earthbending: feet rooted, will against the mountain. For the first time the ground answered him.",
            "Bài học không dịu dàng. Toph bắt Aang ngã, rồi đứng. Đá chỉ nhường người không sợ. Cậu học được điều đó.",
            "The lesson was not gentle. Toph let Aang fall, then stand. Stone yields only to those who do not flinch. He learned that.",
        ),
    ),
    page(
        "s2-azula",
        "/illustrations/s2-04.jpg",
        "s2-page-04",
        {"vi": "Azula", "en": "Azula"},
        t(
            "Có cô Azula. Azula theo sau. Azula thổi lửa xanh. Các bạn chạy.",
            "This is Azula. Azula follows them. Azula blows blue fire. The friends run.",
            "Azula là em Zuko. Cô ấy đuổi theo trên đường. Các bạn phải chạy nhanh.",
            "Azula is Zuko's sister. She chased them on the road. The friends had to run fast.",
            "Công chúa Azula săn Đội Avatar với lửa xanh. Cô nhanh, khôn, và không bỏ cuộc. Appa phải bay.",
            "Princess Azula hunted Team Avatar with blue fire. She was fast, clever, and would not stop. Appa had to fly.",
            "Azula hiện như một vệt lửa lạnh. Không phải sức mạnh làm mọi người sợ — mà sự chắc chắn. Cô luôn tin mình sẽ tới trước.",
            "Azula arrived like a cold streak of flame. It was not her power that frightened them — it was her certainty. She always believed she would arrive first.",
        ),
    ),
    page(
        "s2-appa-gone",
        "/illustrations/s2-05.jpg",
        "s2-page-05",
        {"vi": "Appa mất", "en": "Appa Lost"},
        t(
            "Appa mất rồi. Aang buồn lắm. Aang ngồi. Bạn bè ở đó.",
            "Appa is gone. Aang is so sad. Aang sat down. His friends stayed with him.",
            "Một ngày Appa biến mất. Aang khóc. Katara, Sokka và Toph ở bên cậu.",
            "One day Appa disappeared. Aang cried. Katara, Sokka, and Toph stayed beside him.",
            "Appa bị bắt. Aang gục trên đồi. Nỗi nhớ con bò bay lớn hơn cả gió. Bạn bè không để cậu một mình.",
            "Appa was taken. Aang sank on a hillside. Missing the flying bison hurt more than the wind. His friends would not leave him alone.",
            "Mất Appa là mất một nửa bầu trời. Aang ngồi im, như đứa trẻ bị lấy đi giấc mơ. Những người bạn đứng sau lưng — một vòng tay không nói.",
            "Losing Appa was losing half the sky. Aang sat still, a child with a dream stolen. His friends stood behind him — a circle of arms that did not need words.",
        ),
    ),
    page(
        "s2-search",
        "/illustrations/s2-06.jpg",
        "s2-page-06",
        {"vi": "Tìm", "en": "Search"},
        t(
            "Mấy bạn tìm Appa. Hỏi người ta. Bay tiếp. Tìm mãi.",
            "The friends look for Appa. They ask people. They fly on. They keep looking.",
            "Họ đi khắp nơi để tìm Appa. Có người thấy, có người không. Họ không bỏ cuộc.",
            "They went everywhere to find Appa. Some people had seen him. Some had not. They did not give up.",
            "Đội Avatar lùng khắp Thổ quốc. Từng tin đồn, từng dấu chân. Toph lắng nghe đất, Aang lắng nghe gió.",
            "Team Avatar searched the Earth Kingdom. Every rumor, every track. Toph listened to the ground. Aang listened to the wind.",
            "Họ lần theo bóng Appa như lần theo một bài hát cũ. Đất rộng, tin đồn mỏng, nhưng tình bạn là sợi chỉ không đứt.",
            "They followed Appa's shadow like an old song. The land was wide, the rumors thin, but friendship was a thread that would not break.",
        ),
    ),
    page(
        "s2-city",
        "/illustrations/s2-07.jpg",
        "s2-page-07",
        {"vi": "Thành to", "en": "The City"},
        t(
            "Có thành phố to. Tường cao lắm. Các bạn vào trong.",
            "There is a big city. The wall is so tall. The friends go inside.",
            "Họ tới một thành phố rất lớn. Tường thành cao như núi. Bên trong có nhiều người.",
            "They came to a very big city. The walls were as high as mountains. Many people lived inside.",
            "Ba Sinh Thế — thành phố có tường lớn nhất thế giới. Đội Avatar hy vọng Appa ở đây, và hy vọng được yên.",
            "Ba Sing Se — the city with the greatest walls in the world. Team Avatar hoped Appa was here, and hoped for rest.",
            "Ba Sinh Thế đội tường lên trời, như muốn giấu cả một quốc gia. Họ bước vào, nhỏ như hạt bụi, mang theo một cái tên: Appa.",
            "Ba Sing Se lifted its walls to the sky, as if to hide a nation. They entered, small as dust, carrying one name: Appa.",
        ),
    ),
    page(
        "s2-found",
        "/illustrations/s2-08.jpg",
        "s2-page-08",
        {"vi": "Appa về", "en": "Appa Home"},
        t(
            "Appa về rồi. Aang ôm Appa. Appa liếm Aang. Vui lắm.",
            "Appa is back. Aang hugged Appa. Appa licked Aang. So happy.",
            "Họ tìm thấy Appa trong hang. Aang ôm chặt. Mọi người khóc vui.",
            "They found Appa in a cave. Aang hugged him tight. Everyone cried happy tears.",
            "Dưới lòng đất, Appa đang chờ. Aang lao tới, mặt ướt. Con bò bay thở ra một hơi dài, như cả mùa đông vừa tan.",
            "Under the earth, Appa was waiting. Aang ran to him, face wet. The flying bison breathed out a long breath, as if a whole winter had melted.",
            "Cuộc hội ngộ không cần lời. Lông Appa, nước mắt Aang, ánh tinh thể xanh. Thế giới, trong một phút, đúng chỗ trở lại.",
            "The reunion needed no speech. Appa's fur, Aang's tears, the green crystal light. For a minute the world sat back in its right place.",
        ),
    ),
    page(
        "s2-palace",
        "/illustrations/s2-09.jpg",
        "s2-page-09",
        {"vi": "Trong thành", "en": "In the City"},
        t(
            "Azula vào thành. Azula hông hiền. Mọi người lo.",
            "Azula came into the city. Azula is not kind. People worried.",
            "Azula cũng vào thành phố lớn. Cô ấy muốn bắt Aang. Các bạn phải cẩn thận.",
            "Azula also entered the great city. She wanted to catch Aang. The friends had to be careful.",
            "Azula lọt vào cung điện Ba Sinh Thế. Thành phố tưởng mình an toàn. Đội Avatar biết chuyện sẽ khó.",
            "Azula slipped into the palace of Ba Sing Se. The city thought it was safe. Team Avatar knew trouble was coming.",
            "Lửa xanh đứng trên bậc cung. Thành phố lớn nhất thế giới vẫn có thể bị đánh lừa. Aang và bạn bè đứng quá nhỏ trước sân ấy.",
            "Blue fire stood on the palace steps. The greatest city in the world could still be fooled. Aang and his friends looked very small in that courtyard.",
        ),
    ),
    page(
        "s2-sleep",
        "/illustrations/s2-10.jpg",
        "s2-page-10",
        {"vi": "Aang ngủ", "en": "Aang Sleeps"},
        t(
            "Aang mệt lắm. Aang ngủ. Bạn bè ẵm Aang. Chuyện còn nữa. Ngủ ngon nha.",
            "Aang was so tired. Aang slept. Friends carried Aang. The story goes on. Night night.",
            "Aang bị thương và ngủ một giấc dài. Bạn bè đưa cậu đi. Mùa hai kết thúc. Mùa ba sẽ tới.",
            "Aang was hurt and slept a long sleep. His friends carried him away. Season two ends. Season three will come.",
            "Aang ngã xuống, kiệt sức. Katara giữ cậu. Đội Avatar rời thành phố trong đêm. Mùa đất khép lại — chưa phải hết.",
            "Aang fell, exhausted. Katara held him. Team Avatar left the city in the night. The Earth season closes — but it is not the end.",
            "Cậu ngủ trên lưng Appa như một lời hứa chưa xong. Bạn bè chèo lấy gió. Mùa đất lặng đi, để mùa lửa còn phải nói.",
            "He slept on Appa's back like an unfinished promise. His friends took the wind. The Earth season grew quiet, so the Fire season would still have something to say.",
        ),
    ),
]

s3_pages = [
    page(
        "s3-cover",
        "/illustrations/s3-00.jpg",
        "s3-page-00",
        {"vi": "Mùa lửa", "en": "Fire Season"},
        t(
            "Đây là chuyện Aang. Mùa ba. Aang thức dậy. Aang còn việc.",
            "This is Aang. Season three. Aang wakes up. Aang still has work to do.",
            "Đây là mùa ba. Aang mở mắt. Trời đỏ. Cậu phải gặp ông Ozai.",
            "This is season three. Aang opens his eyes. The sky is red. He still has to face Ozai.",
            "Mùa lửa mở ra trên vách đá. Aang tỉnh, nhỏ bé trước biển Hỏa quốc. Sao chổi đang tới.",
            "The Fire season opens on a cliff. Aang wakes, small before the Fire Nation sea. A comet is coming.",
            "Mùa lửa không dịu. Trời cháy ở chân trời, và đứa trẻ từng thổi gió phải học cách đứng trước một ông vua.",
            "The Fire season is not gentle. The sky burns at the horizon, and the child who once blew the wind must learn to stand before a king.",
        ),
    ),
    page(
        "s3-wake",
        "/illustrations/s3-01.jpg",
        "s3-page-01",
        {"vi": "Thức dậy", "en": "Wake Up"},
        t(
            "Aang mở mắt. Katara ở đó. Sokka ở đó. Toph ở đó. Aang cười.",
            "Aang opened his eyes. Katara was there. Sokka was there. Toph was there. Aang smiled.",
            "Aang tỉnh dậy trong ngôi đền cũ. Bạn bè ngồi quanh. Cậu yếu, nhưng vui.",
            "Aang woke in an old temple. His friends sat around him. He was weak, but glad.",
            "Ánh nắng chạm mặt Aang. Đội Avatar đã giữ cậu suốt những ngày cậu ngủ. Cậu trở về với họ.",
            "Sunlight touched Aang's face. Team Avatar had kept him through the days he slept. He came back to them.",
            "Giấc ngủ dài khép lại. Những khuôn mặt quen — nước, đất, gió — chờ sẵn. Cậu chưa mạnh, nhưng cậu không còn một mình.",
            "The long sleep closed. Familiar faces — water, earth, wind — were waiting. He was not strong yet, but he was not alone.",
        ),
    ),
    page(
        "s3-zuko",
        "/illustrations/page-zuko.jpg",
        "s3-page-02",
        {"vi": "Zuko giúp", "en": "Zuko Helps"},
        t(
            "Zuko tới. Zuko muốn làm bạn. Zuko dạy Aang lửa. Aang tin.",
            "Zuko came. Zuko wants to be a friend. Zuko teaches Aang fire. Aang trusts him.",
            "Zuko tìm Aang và xin lỗi. Cậu muốn giúp. Aang suy nghĩ, rồi gật đầu.",
            "Zuko found Aang and said sorry. He wanted to help. Aang thought, then nodded.",
            "Hoàng tử Zuko đến Tây Phong Đền, không phải để bắt, mà để dạy. Lòng cậu đã đổi. Aang cho cậu một cơ hội.",
            "Prince Zuko came to the Western Air Temple not to hunt, but to teach. His heart had turned. Aang gave him a chance.",
            "Kẻ từng đuổi theo giờ đứng xin được đứng cùng. Zuko đưa ra lửa như một lời chuộc. Aang, vốn tha thứ như thở, nhận lấy.",
            "The hunter now asked to stand with them. Zuko offered fire like a repayment. Aang, who forgave the way he breathed, took it.",
        ),
    ),
    page(
        "s3-dragons",
        "/illustrations/s3-03.jpg",
        "s3-page-03",
        {"vi": "Rồng", "en": "Dragons"},
        t(
            "Có hai con rồng. Rồng đẹp lắm. Rồng dạy lửa ấm. Hông phải giận.",
            "There are two dragons. The dragons are so pretty. They teach warm fire. Not angry fire.",
            "Aang và Zuko gặp rồng. Rồng dạy rằng lửa thật là sự sống, không phải sự giận.",
            "Aang and Zuko met dragons. The dragons taught that true fire is life, not anger.",
            "Hai rồng cổ múa trên đỉnh núi, trao lại hỏa thuật nguyên bản: hơi ấm của mặt trời, không phải ngọn lửa của căm thù.",
            "Two ancient dragons danced on a mountain peak and gave back the original firebending: the warmth of the sun, not the flame of hate.",
            "Rồng không dạy đốt. Chúng dạy sống. Aang hiểu: lửa cũng có thể giữ người ta ấm, như gió giữ người ta bay.",
            "The dragons did not teach burning. They taught living. Aang understood: fire can keep people warm, the way wind keeps people flying.",
        ),
    ),
    page(
        "s3-eclipse",
        "/illustrations/s3-04.jpg",
        "s3-page-04",
        {"vi": "Trời tối", "en": "Dark Day"},
        t(
            "Trời tối giữa ngày. Các bạn thử. Hông được. Các bạn về.",
            "The sky went dark in the day. The friends tried. It did not work. The friends went home.",
            "Có ngày mặt trời bị che. Lửa yếu. Các bạn tấn công, nhưng phải rút.",
            "There was a day the sun was covered. Fire grew weak. The friends attacked, but they had to leave.",
            "Nhật thực đến. Hỏa thuật tắt. Đội Avatar và quân xâm lược không thắng. Họ rút về, còn việc chưa xong.",
            "The eclipse came. Firebending died. Team Avatar and the invasion did not win. They pulled back, the work unfinished.",
            "Ngày đen — mặt trời nuốt chính nó. Cơ hội mỏng như lưỡi dao. Họ không đủ. Im lặng sau nhật thực nặng hơn tiếng trống.",
            "The dark day — the sun swallowed itself. The chance was thin as a blade. They were not enough. The quiet after the eclipse weighed more than drums.",
        ),
    ),
    page(
        "s3-comet",
        "/illustrations/s3-05.jpg",
        "s3-page-05",
        {"vi": "Sao chổi", "en": "The Comet"},
        t(
            "Có sao chổi đỏ. Sao to lắm. Phải lo. Aang nhìn trời.",
            "There is a red comet. The star is so big. They must be careful. Aang looked at the sky.",
            "Một sao chổi lớn đang tới. Ozai sẽ mạnh hơn. Các bạn phải sẵn sàng.",
            "A great comet is coming. Ozai will be stronger. The friends must get ready.",
            "Sao chổi Sozin kéo lửa đỏ qua đêm. Hỏa vương sẽ thừa cơ. Thời gian của Aang còn rất ít.",
            "Sozin's comet dragged red fire across the night. The Fire Lord would use it. Aang had very little time.",
            "Sao chổi không phải điềm lành. Nó là đồng hồ. Mỗi tia đỏ nhắc Aang: thế giới đang chờ một đứa trẻ chọn cách không đốt.",
            "The comet was not a blessing. It was a clock. Every red spark reminded Aang: the world was waiting for a child to choose a way that would not burn.",
        ),
    ),
    page(
        "s3-ready",
        "/illustrations/page-07.jpg",
        "s3-page-06",
        {"vi": "Sẵn sàng", "en": "Ready"},
        t(
            "Mấy bạn đứng chung. Aang. Katara. Sokka. Toph. Zuko. Appa. Momo. Sẵn sàng.",
            "The friends stood together. Aang. Katara. Sokka. Toph. Zuko. Appa. Momo. Ready.",
            "Cả đội đứng trên đồi. Họ tin nhau. Họ sẽ làm phần của mình.",
            "The whole team stood on a hill. They trusted one another. Each would do their part.",
            "Đội Avatar chia việc: ai giữ Azula, ai giữ thành, ai đi với Aang. Hoàng hôn ấy, họ là một.",
            "Team Avatar split the work: who would hold Azula, who the city, who would go with Aang. That sunset, they were one.",
            "Không bài diễn văn. Chỉ một hàng người trên gió chiều. Họ đã đi quá xa để quay lại. Họ bước tới.",
            "No speech. Only a line of people in the evening wind. They had come too far to turn back. They stepped forward.",
        ),
    ),
    page(
        "s3-ozai",
        "/illustrations/page-08.jpg",
        "s3-page-07",
        {"vi": "Ông Ozai", "en": "Ozai"},
        t(
            "Ông Ozai hông hiền. Ozai muốn đốt. Aang đứng đó. Aang hông muốn đánh.",
            "Ozai is not kind. Ozai wants to burn. Aang stood there. Aang did not want to hit him.",
            "Aang đối diện Hỏa vương. Ozai rất mạnh. Aang vẫn không muốn làm đau ông ta.",
            "Aang faced the Fire Lord. Ozai was very strong. Aang still did not want to hurt him.",
            "Dưới sao chổi, Aang và Ozai gặp nhau. Một đứa trẻ, một ông vua. Aang tìm đường không giết.",
            "Under the comet, Aang and Ozai met. A child, a king. Aang looked for a path that would not kill.",
            "Ozai là lửa không có mặt trời — chỉ thiêu. Aang nhớ rồng, nhớ gió, nhớ lời hứa không nhuốm máu. Cậu đứng yên trước cơn bão.",
            "Ozai was fire without a sun — only burning. Aang remembered the dragons, the wind, the promise not to stain his hands. He stood still in the storm.",
        ),
    ),
    page(
        "s3-take",
        "/illustrations/page-09.jpg",
        "s3-page-08",
        {"vi": "Cách hay", "en": "A Good Way"},
        t(
            "Aang lấy lửa của Ozai. Ozai hông đốt nữa. Aang giỏi lắm.",
            "Aang took Ozai's fire away. Ozai could not burn things. Aang did so well.",
            "Aang lấy đi sức lửa của Ozai. Ông ta không đốt được nữa. Không ai phải chết.",
            "Aang took Ozai's fire power away. He could not burn things anymore. Nobody had to die.",
            "Aang dùng năng lực Avatar tước hỏa thuật của Ozai. Hòa bình không cần một mạng người.",
            "Aang used the Avatar's gift to take Ozai's firebending. Peace did not need a life.",
            "Cậu lấy đi ngọn lửa, không lấy đi hơi thở. Đó là cách của Phong tộc, cách của một đứa trẻ vẫn tin người ta có thể đổi.",
            "He took the flame and left the breath. That was the Air Nomad way, the way of a child who still believed people could change.",
        ),
    ),
    page(
        "s3-king",
        "/illustrations/s3-09.jpg",
        "s3-page-09",
        {"vi": "Vua mới", "en": "New Lord"},
        t(
            "Zuko làm vua mới. Zuko cười. Người ta vui. Hông đốt nữa.",
            "Zuko is the new lord. Zuko smiled. People were happy. No more burning.",
            "Zuko trở thành Hỏa vương mới. Cậu hứa giữ hòa bình. Mọi người vỗ tay.",
            "Zuko became the new Fire Lord. He promised to keep the peace. Everyone clapped.",
            "Zuko bước ra bậc cung, không phải kẻ săn, mà người gìn giữ. Hỏa quốc thở ra.",
            "Zuko stepped onto the palace stairs, not a hunter, but a keeper. The Fire Nation exhaled.",
            "Vết sẹo vẫn đó. Ngai thì mới. Zuko cúi đầu trước dân mình như người đã nợ một thế giới, và bắt đầu trả.",
            "The scar remained. The throne was new. Zuko bowed to his people like someone who owed a world, and began to pay.",
        ),
    ),
    page(
        "s3-peace",
        "/illustrations/page-09.jpg",
        "s3-page-10",
        {"vi": "Hòa bình", "en": "Peace"},
        t(
            "Mọi người vui. Trời nắng đẹp. Aang cười. Hết chuyện rồi. Ngủ ngon nha.",
            "Everyone was happy. The sun was warm. Aang smiled. The end. Night night.",
            "Hòa bình trở lại. Bạn bè ngồi với nhau. Câu chuyện kết thúc. Ngủ ngon nhé.",
            "Peace came back. The friends sat together. The story is over. Good night.",
            "Nắng phủ bốn quốc gia. Đội Avatar còn đó — nước, đất, lửa, gió. Chuyện khép lại. Chúc ngủ ngon.",
            "Sunlight covered the four nations. Team Avatar remained — water, earth, fire, wind. The tale closes. Good night.",
            "Thế giới thở ra. Aang, vẫn là đứa trẻ thổi gió, được phép chỉ còn là bạn. Chuyện đến đây là hết. Ngủ ngon, và mơ những giấc êm.",
            "The world exhaled. Aang, still the child who blew the wind, was allowed to be only a friend. Here the tale is done. Sleep well, and dream gently.",
        ),
    ),
]

s1 = {
    "id": "s1",
    "vi": "Mùa 1 · Nước",
    "en": "Season 1 · Water",
    "tagline": story["tagline"],
    "pages": story["pages"],
}
s2 = {
    "id": "s2",
    "vi": "Mùa 2 · Đất",
    "en": "Season 2 · Earth",
    "tagline": {"vi": "Aang học đất", "en": "Aang learns earth"},
    "pages": s2_pages,
}
s3 = {
    "id": "s3",
    "vi": "Mùa 3 · Lửa",
    "en": "Season 3 · Fire",
    "tagline": {"vi": "Aang gặp lửa", "en": "Aang meets fire"},
    "pages": s3_pages,
}

out = {
    "appName": story["appName"],
    "tagline": story["tagline"],
    "levels": story["levels"],
    "seasons": [s1, s2, s3],
}
root.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n")
print("seasons", [s["id"] for s in out["seasons"]], "pages", [len(s["pages"]) for s in out["seasons"]])
